<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
import { api, type Data } from '../api/client'
import { confirmAction } from '../lib/ui'
const saved=ref<Data|null>(null), busy=ref(false), error=ref(''), result=ref('')
const form=reactive({provider:'openai-compatible',model:'',base_url:'',api_key:'',embedding_mode:'keyword',embedding_model:'',embedding_base_url:'',input_budget:24000})
async function load(){const s=await api.get('/settings/ai');saved.value=s;for(const k of ['provider','model','base_url','embedding_mode','embedding_model','embedding_base_url','input_budget'] as const){if(s[k])Object.assign(form,{[k]:s[k]})}form.api_key=''}
async function act(fn:()=>Promise<void>){busy.value=true;error.value='';result.value='';try{await fn()}catch(e){error.value=(e as Error).message}finally{busy.value=false}}
async function save(){await act(async()=>{const payload:Data={...form};if(!form.api_key)delete payload.api_key;await api.put('/settings/ai',payload);await load();result.value='配置已保存，尚未验证服务可用。'})}
async function test(){await act(async()=>{await api.post('/settings/ai/test');result.value='本次真实模型请求成功（不代表持续在线）。'})}
async function reset(){if(await confirmAction('删除个人 AI 配置并恢复服务器默认配置？'))await act(async()=>{await api.delete('/settings/ai');await load()})}
onMounted(()=>act(load))
</script>
<template><section class="panel ai-settings"><div class="panel-head"><div><h2>个人 AI 设置</h2><p>按账户加密保存；密钥不会回显。对话及选中的资料片段会发送给你配置的供应商。</p></div></div><div class="pad"><p>{{saved?.configured?'已配置 · 可用性需真实测试':'尚未配置'}} · {{saved?.source==='personal'?'个人配置':'服务器默认'}}</p><p v-if="error" class="error-banner" role="alert">{{error}}</p><p v-if="result" role="status">{{result}}</p><form class="stack-form" @submit.prevent="save"><fieldset :disabled="busy"><label>接口类型<select v-model="form.provider"><option v-for="p in ['openai-compatible','openai','deepseek','qwen','gemini']" :key="p" :value="p">{{p}}</option></select></label><label>模型 ID<input v-model.trim="form.model" required maxlength="200"/></label><p class="field-help">请原样填写供应商控制台提供的精确模型 ID（区分大小写）。ChatGPT、DeepSeek 等品牌名不一定是可调用 ID；中转平台可能使用自定义别名，请以该平台文档为准。</p><label>API 基础地址<input v-model.trim="form.base_url" type="url" placeholder="https://api.example.com/v1" maxlength="500"/></label><label>API Key<input v-model="form.api_key" type="password" autocomplete="new-password" maxlength="4096" placeholder="留空保留已有个人密钥；首次保存必须填写"/></label><p class="field-help">更改服务商或地址必须重新填写密钥。测试仅使用已保存配置，发送固定问候，可能产生少量费用。保存不会自动测试。</p></fieldset><div class="actions"><button class="primary" :disabled="busy">保存 AI 配置</button><button type="button" class="secondary" :disabled="busy||!saved?.configured" @click="test">测试已保存连接</button><button type="button" class="secondary" :disabled="busy" @click="act(load)">重新读取 AI 配置</button><button type="button" class="danger" :disabled="busy||saved?.source!=='personal'" @click="reset">删除个人配置</button><RouterLink to="/chat">进入 AI 对话</RouterLink></div></form></div></section></template>
<style scoped>.ai-settings{margin-bottom:24px}.actions{display:flex;flex-wrap:wrap;gap:12px;align-items:center}fieldset{border:0;padding:0;display:grid;gap:14px;min-width:0}input,select{width:100%}</style>
