<script setup lang="ts">
import { computed, nextTick, onMounted, ref, watch } from 'vue'
import { api, stream, type Data } from '../api/client'
import { useRequest } from '../composables/useRequest'
import { confirmAction } from '../lib/ui'
import PageHeader from '../components/PageHeader.vue'
import EmptyState from '../components/EmptyState.vue'
import MarkdownContent from '../components/MarkdownContent.vue'
import Icon from '../components/Icon.vue'
const { run, busy, error } = useRequest()
const conversations=ref<Data[]>([]), messages=ref<Data[]>([]), bases=ref<Data[]>([]), config=ref<Data|null>(null)
const current=ref<Data|null>(null), draft=ref(''), search=ref(''), mode=ref('tutor'), selectedBase=ref('')
const generating=ref(false), generationId=ref(''), controller=ref<AbortController|null>(null), messageBox=ref<HTMLElement>()
const modes=[['tutor','学习辅导'],['general','通用助手'],['paper','学术写作'],['english','英语老师'],['code','编程导师'],['math','数学导师']]
const filtered=computed(()=>conversations.value.filter(x=>!search.value||x.title.toLowerCase().includes(search.value.toLowerCase())))
const modeName=computed(()=>modes.find(x=>x[0]===mode.value)?.[1]||'学习辅导')
async function scroll(){await nextTick();if(messageBox.value)messageBox.value.scrollTop=messageBox.value.scrollHeight}
async function refresh(){const [c,k,s]=await Promise.all([api.get<Data[]>('/conversations'),api.get<Data[]>('/knowledge-bases'),api.get('/settings/ai')]);conversations.value=c;bases.value=k;config.value=s;if(current.value){const fresh=c.find(x=>x.id===current.value?.id);if(fresh)current.value=fresh}}
async function create(){await run(async()=>{const item=await api.post('/conversations',{title:'新对话',mode:mode.value});await refresh();await choose(item)},'新对话已创建')}
async function choose(item:Data){if(generating.value)return;current.value=item;mode.value=item.mode;messages.value=await api.get(`/conversations/${item.id}/messages`);await scroll()}
async function changeMode(){if(!current.value)return;await run(async()=>{current.value=await api.patch(`/conversations/${current.value!.id}`,{mode:mode.value});await refresh()},'对话模式已更新')}
async function rename(item:Data){const title=window.prompt('新的对话标题',item.title);if(!title?.trim())return;await run(async()=>{await api.patch(`/conversations/${item.id}`,{title:title.trim()});await refresh()},'标题已更新')}
async function remove(item:Data){if(!await confirmAction(`删除对话「${item.title}」？`))return;await run(async()=>{await api.delete(`/conversations/${item.id}`);if(current.value?.id===item.id){current.value=null;messages.value=[]}await refresh()},'对话已删除')}
function onEvent(event:string,data:Data){if(event==='message_start'){generationId.value=data.generation_id;messages.value.push({id:data.message_id,role:'assistant',content:'',status:'generating'})}else if(event==='token'){const last=messages.value.at(-1);if(last?.role==='assistant')last.content+=data.content||''}else if(event==='error'){throw new Error(data.message||'生成失败')}else if(event==='message_end'){const last=messages.value.at(-1);if(last)last.status=data.status}void scroll()}
async function generate(regenerate=false){if(!current.value){await create();if(!current.value)return}const content=draft.value.trim();if(!regenerate&&!content)return;if(!config.value?.configured){error.value='AI 模型尚未配置，请先到空间设置完成配置。';return}if(!regenerate){messages.value.push({role:'user',content,status:'completed'});draft.value=''}generating.value=true;error.value='';controller.value=new AbortController();try{await stream(`/conversations/${current.value.id}/${regenerate?'regenerate':'messages'}`,regenerate?{}:{content,knowledge_base_id:selectedBase.value||null},controller.value.signal,onEvent);await refresh();messages.value=await api.get<Data[]>(`/conversations/${current.value.id}/messages`)}catch(e){if((e as Error).name!=='AbortError'){error.value=(e as Error).message;if(!regenerate&&!generationId.value)draft.value=content}try{messages.value=await api.get<Data[]>(`/conversations/${current.value.id}/messages`)}catch{/* preserve current partial messages */}}finally{generating.value=false;generationId.value='';controller.value=null;await scroll()}}
async function stop(){if(generationId.value)await api.post(`/generations/${generationId.value}/cancel`);controller.value?.abort();generating.value=false}
function submit(e:KeyboardEvent){if(e.key==='Enter'&&!e.shiftKey){e.preventDefault();void generate()}}
async function copyText(value:string){await window.navigator.clipboard.writeText(value)}
watch(()=>current.value?.id,scroll);onMounted(()=>run(refresh))
</script>
<template><section class="page chat-page"><PageHeader title="AI 学习助手" eyebrow="可验证的真实模型连接" description="六种学习模式、连续上下文、流式回答，并可限定只依据你的知识库作答"><button class="primary" :disabled="busy" @click="create"><Icon name="plus" :size="17"/>新对话</button></PageHeader>
<div v-if="error" class="error-banner" role="alert"><Icon name="question" :size="17"/>{{error}}<RouterLink v-if="!config?.configured" class="text-button" to="/settings">前往配置</RouterLink></div>
<div class="ai-status-strip" :class="{configured:config?.configured}"><span class="status-pulse"></span><strong>{{config?.configured?'模型配置已保存（未验证在线）':'模型服务未配置'}}</strong><span>{{config?.configured?`${config.model} · 流式传输已启用`:'在空间设置中填写模型服务后即可使用'}}</span></div>
<div class="chat-layout"><aside class="panel conversation-panel"><div class="panel-head"><div><h2>对话记录</h2><p>{{conversations.length}} 个真实会话</p></div></div><label class="conversation-search"><Icon name="search" :size="15"/><input v-model="search" placeholder="搜索对话…"/></label><div class="conversation-scroll"><div v-for="item in filtered" :key="item.id" class="conversation-row" :class="{selected:current?.id===item.id}"><button class="conversation-select" @click="choose(item)"><Icon name="spark" :size="16"/><div><strong>{{item.title}}</strong><small>{{modes.find(x=>x[0]===item.mode)?.[1]}}</small></div></button><div class="conversation-controls"><button class="icon-button" title="重命名" @click="rename(item)"><Icon name="edit" :size="14"/></button><button class="icon-button danger-text" title="删除" @click="remove(item)"><Icon name="trash" :size="14"/></button></div></div><EmptyState v-if="!filtered.length" title="还没有对话" description="创建对话，开始一次有上下文的学习。" icon="spark"/></div><div class="conversation-foot"><Icon name="shield" :size="14"/>对话按账户隔离保存</div></aside>
<main class="panel chat-main"><header class="chat-head"><div><strong>{{current?.title||'准备开始学习'}}</strong><small>{{selectedBase?`仅依据：${bases.find(x=>x.id===selectedBase)?.name}`:`${modeName} · 通用模型知识`}}</small></div><div class="chat-head-controls"><select v-model="selectedBase" :disabled="generating"><option value="">不限定知识库</option><option v-for="base in bases" :key="base.id" :value="base.id">资料限定 · {{base.name}}</option></select><select v-model="mode" :disabled="generating" @change="changeMode"><option v-for="item in modes" :key="item[0]" :value="item[0]">{{item[1]}}</option></select></div></header>
<div ref="messageBox" class="messages"><div v-if="!messages.length" class="chat-welcome"><div class="welcome-orb"><Icon name="spark" :size="30"/></div><h2>把问题讲清楚，也把依据讲明白</h2><p>选择辅导模式后直接提问；选择知识库后，回答将受资料约束并标注引用编号。</p><div class="suggestions"><button v-for="text in ['帮我拆解今天最重要的学习任务','用苏格拉底式提问带我理解一个概念','根据知识库梳理期末复习框架']" :key="text" @click="draft=text"><Icon name="spark" :size="15"/>{{text}}<Icon name="arrow" :size="15"/></button></div></div>
<article v-for="message in messages" :key="message.id||message.created_at" class="message" :class="message.role"><div class="message-avatar">{{message.role==='user'?'我':'AI'}}</div><div class="message-body"><div class="message-label"><strong>{{message.role==='user'?'你':'StudyMind'}}</strong><span v-if="message.status==='generating'" class="typing">正在思考</span><span v-else-if="message.status==='cancelled'">已停止</span><span v-else-if="message.status==='failed'" class="danger-text">生成失败</span></div><p v-if="message.role==='user'" class="user-content">{{message.content}}</p><MarkdownContent v-else :content="message.content||'正在连接模型…'"/><button v-if="message.content" class="message-copy text-button" @click="copyText(message.content)"><Icon name="copy" :size="13"/>复制</button></div></article></div>
<footer class="chat-composer-wrap"><div class="chat-toolbar"><span>{{selectedBase?'已启用知识库约束':'未限定资料来源'}}</span><button v-if="messages.some(x=>x.role==='assistant')&&!generating" class="text-button" @click="generate(true)"><Icon name="refresh" :size="14"/>重新生成</button></div><div class="chat-composer" :class="{active:draft}"><textarea v-model="draft" rows="2" maxlength="20000" :disabled="generating||!config?.configured" placeholder="输入学习问题，Enter 发送，Shift + Enter 换行…" @keydown="submit"></textarea><button v-if="generating" class="stop-button" @click="stop"><Icon name="stop" :size="16"/>停止</button><button v-else class="send-button" :disabled="!draft.trim()||!config?.configured" title="发送" @click="generate()"><Icon name="send" :size="18"/></button></div><p class="composer-note">AI 可能出错；知识库模式会限制资料范围，但关键结论仍请核对原文。</p></footer></main></div></section></template>