<script setup lang="ts">
import { computed, onMounted, reactive, ref, watch } from 'vue'
import { useRoute } from 'vue-router'
const route = useRoute()
import { api, downloadFile, type Data } from '../api/client'
import { useRequest } from '../composables/useRequest'
import { confirmAction, statusText } from '../lib/ui'
import PageHeader from '../components/PageHeader.vue'
import Icon from '../components/Icon.vue'
import EmptyState from '../components/EmptyState.vue'
const { run, busy, error } = useRequest(); const fileInput = ref<HTMLInputElement>(); const documents = ref<Data[]>([]); const bases = ref<Data[]>([]); const selected = ref<Data | null>(null); const detail = ref<Data | null>(null); const loaded = ref(false); const preview = ref(false); const baseDialog = ref(false); const baseForm = reactive({ name: '', description: '' }); const filter = ref(''); const selectedBase = ref(''); const folder = ref('')
const filtered = computed(() => documents.value.filter(x => !filter.value || x.original_name.toLowerCase().includes(filter.value.toLowerCase())))
async function refresh() { const [d, k] = await Promise.all([api.get<Data[]>('/documents'), api.get<Data[]>('/knowledge-bases')]); documents.value = d; bases.value = k; loaded.value = true; if (selected.value) { const current = d.find(x => x.id === selected.value?.id); if (current) selected.value = current } }
async function load() { await run(async () => { await refresh(); const doc = documents.value.find(x => x.id === route.query.id); if (doc) await loadDetail(doc) }) }
watch(() => route.query.id, () => { if (loaded.value) void load() })
async function loadDetail(doc: Data) { const data = await api.get(`/documents/${doc.id}`); selected.value = doc; detail.value = data; selectedBase.value = data.link?.knowledge_base_id || ''; folder.value = data.link?.folder || ''; preview.value = true }
async function choose(doc: Data) { await run(() => loadDetail(doc)) }
async function upload(event?: Event) { const file = (event?.target as HTMLInputElement)?.files?.[0]; if (!file) return; const data = new FormData(); data.append('file', file); await run(async () => { const doc = await api.post('/documents/upload', data); await refresh(); await loadDetail(doc) }, '文件已上传并完成解析'); if (event) (event.target as HTMLInputElement).value = '' }
async function link() { if (!selected.value) return; await run(async () => { await api.patch(`/documents/${selected.value!.id}/knowledge-base`, { knowledge_base_id: selectedBase.value || null, folder: folder.value }); await refresh(); if (detail.value) detail.value.link = { ...detail.value.link, knowledge_base_id: selectedBase.value || null, folder: folder.value } }, '文档归档已更新') }
async function index() { const doc = selected.value; if (!doc) return; await run(async () => { await api.post(`/documents/${doc.id}/index`); await refresh(); await loadDetail(doc) }, '文档索引已完成') }

async function remove(doc: Data) { if (!await confirmAction(`删除「${doc.original_name}」？原文件、分块和索引都会删除。`)) return; await run(async () => { await api.delete(`/documents/${doc.id}`); if (selected.value?.id === doc.id) { selected.value = null; detail.value = null; preview.value = false }; await refresh() }, '文档已删除') }
async function createBase() { await run(async () => { await api.post('/knowledge-bases', baseForm); baseForm.name = ''; baseForm.description = ''; baseDialog.value = false; await refresh() }, '知识库已创建') }
onMounted(load)
</script>
<template><section class="page">
  <PageHeader title="资料管理" eyebrow="把资料沉淀为自己的知识" description="上传、文字识别、预览、归档并建立本地检索索引"><button class="secondary" :disabled="busy" @click="baseDialog = true"><Icon name="layers" :size="17" /> 新建知识库</button><button class="primary" :disabled="busy" @click="fileInput?.click()"><Icon name="upload" :size="17" /> 上传文档</button><input ref="fileInput" hidden type="file" accept=".txt,.md,.markdown,.csv,.json,.docx,.pdf,.png,.jpg,.jpeg,.webp" @change="upload" /></PageHeader>
  <div v-if="error" class="error-banner" role="alert">{{ error }}<button class="text-button" :disabled="busy" @click="load">重试</button></div><div class="notice"><Icon name="shield" /><p>上传接口会真实提取文本；图片与扫描 PDF 使用本地 OCR。资料仅用于当前账户的归档和检索。</p></div>
  <div class="document-workspace" :class="{ 'has-detail': !!selected }"><section class="panel document-list"><div class="panel-head wrap"><div><h2>我的文档 <span class="count-badge">{{ documents.length }}</span></h2><p>支持 PDF、DOCX、TXT、Markdown、CSV、JSON 与图片</p></div><input v-model="filter" class="compact-input" placeholder="筛选文件名…" aria-label="筛选文件名" /></div><div v-for="doc in filtered" :key="doc.id" class="document-row" :class="{ selected: selected?.id === doc.id }"><button class="document-select" :disabled="busy" @click="choose(doc)"><span class="file-badge">{{ doc.mime_type?.includes('pdf') ? 'PDF' : doc.mime_type?.includes('word') ? 'DOC' : doc.original_name.split('.').pop()?.toUpperCase() || 'FILE' }}</span><span class="grow"><strong>{{ doc.original_name }}</strong><small>{{ Math.ceil((doc.size_bytes || 0) / 1024) }} KB · {{ statusText(doc.status) }}{{ doc.index_mode ? ` · ${statusText(doc.index_mode)}` : '' }}</small><small v-if="doc.summary" class="line-clamp">{{ doc.summary }}</small></span><Icon name="arrow" :size="16" /></button><button class="icon-button danger-text" :disabled="busy" title="删除文档" @click="remove(doc)"><Icon name="trash" :size="16" /></button></div><EmptyState v-if="!filtered.length && loaded" title="还没有学习资料" description="上传一份教材、讲义或笔记，从可检索的内容开始。" icon="file"><button class="secondary" :disabled="busy" @click="fileInput?.click()">选择文件</button></EmptyState></section>
    <aside v-if="selected && detail" class="panel document-detail"><div class="panel-head"><div><h2>{{ selected.original_name }}</h2></div><button class="icon-button" title="关闭预览" @click="selected = null; detail = null"><Icon name="close" /></button></div><div class="document-meta"><span>{{ detail.link?.extraction_method || '文本提取' }}</span><span>{{ detail.link?.page_count || 1 }} 页</span><span>{{ detail.chunks?.length || 0 }} 个分块</span></div><div class="form-row"><label>归属知识库<select v-model="selectedBase"><option value="">不归档</option><option v-for="base in bases" :key="base.id" :value="base.id">{{ base.name }}</option></select></label><label>文件夹<input v-model="folder" maxlength="160" placeholder="例如：期末复习" /></label></div><div class="button-row"><button class="secondary small" :disabled="busy" @click="link">保存归档</button><button class="secondary small" :disabled="busy || detail.link?.index_mode === 'semantic'" @click="index">{{ detail.link?.index_mode === 'semantic' ? '已建立索引' : '建立本地索引' }}</button><button class="secondary small" :disabled="busy" @click="downloadFile(`/documents/${selected.id}/download`, selected.original_name)">下载原文件</button></div><div class="preview-box"><div class="panel-head"><h3>文本预览</h3><button class="text-button" @click="preview = !preview">{{ preview ? '收起' : '展开' }}</button></div><pre v-if="preview">{{ detail.content || detail.chunks?.map((x: Data) => x.content).join('\n\n') || '没有可预览文本' }}</pre></div></aside></div>
  <ElDialog v-model="baseDialog" title="新建知识库" width="520px" :close-on-click-modal="!busy"><form class="stack-form" @submit.prevent="createBase"><label>名称<input v-model.trim="baseForm.name" required maxlength="120" placeholder="例如：数据库课程" /></label><label>描述<textarea v-model="baseForm.description" maxlength="1000" rows="4" /></label><div class="dialog-actions"><button type="button" class="secondary" @click="baseDialog = false">取消</button><button class="primary" :disabled="busy">创建</button></div></form></ElDialog>
</section></template>
